# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94a460f02e5e6ef335b337d1b3e2c0918f9fa2711297cdf2132fc6697cbbe1368dd35f871962ffcf65d2442d35ac0c91ef7eba14e41e766680cbd02299b5bf35

test:
  secret_key_base: 8901441b4b272bd55f0493d2aadb76491c69111edb7ea8f53b3ab1247cf61540dc944df893cc2643441266bc0c710c95b6c55b037d3641a6c46c066f2d6915ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
